dist: xenial
sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - libgtest-dev
    - librtmp-dev
script: make -C ui/linux && make -C ui/linux/tests && cd ui/linux/tests && ./test-all && cd ../../../bvt && cp -R ../ui/linux/peercast-yt . && ruby test-all.rb
notifications:
  webhooks: https://discordapp.com/api/webhooks/397294790728876052/s087VB-hN8g2r-YvX8_HAUPuZCdZ-OA_g6voqTUNg2SIUDn9FhMQRDmxQRIjWWG8-tse/slack
